### ISSUE TITLE
Feature request: Add justGage-style 'reverse' option

### ISSUE THREAD

**Issue by Grayda** [agronick/KGauge#4]
I've got some data that ranges from 20 to -20 that I'd like to display in a gauge, but it looks like KGauge doesn't support reversing the values. The min / max labels appear correctly, with 20 being on the left and -20 being on the right, but the value and the bar itself are stuck at min, as shown in my screenshot (the green arrow indicates where the gauge should be filled to, roughly).

JustGage has [a reverse option](http://justgage.com/examples/reverse.html) that I think would be useful for this library, especially if you wanted to deal with something like disk space remaining as a percent. 100% is good (min), 0% is bad (max)

If this isn't easy to do, then manually overriding the min and max labels would work so I could do `value + 20` then set min to 0 and max to 40 while still giving the appearance of 20 to -20

![image](https://user-images.githubusercontent.com/4891563/58749729-dbf56c80-84cc-11e9-8813-567cbb7960e0.png)

**Comment by agronick** [comment]
I added the ability to have min values larger than max valued and added functions for formatting min and max values.
