### ISSUE TITLE
Justgage 1.3.1

### ISSUE THREAD

**Issue by robertsLando** [agronick/KGauge#6]
HI, I'm a contributor of JustGage project, I'm helping Justgage author to keep it updated. Now with version 1.3.1 Justgage is is CommonJS and AMD friendly, would yoU like to add it as deps and help improving main Justgage project?

**Comment by cahuayamarcial** [comment]
Could you add the pointer?
https://justgage.com/examples/pointer.html

**Comment by robertsLando** [comment]
What you mean? @cahuayamarcial The pointer feature already works

**Comment by cahuayamarcial** [comment]
Project I speak of this "KGauge", without the pointer.

**Comment by agronick** [comment]
If someone wants to make a wrapper for JustGage they can. This fork is intended to be pure Vue so Vue can do the heavy lifting and it can be much smaller in size. 

As for the pointer, you should open up a separate issue or a pull request.
